version: "1"
services:
  juypter:
    container_name: pyeed
    build:
      dockerfile: ./Dockerfile
    ports:
      - '${JUPYTER_PORT}:${JUPYTER_PORT}'

  cytoscape-desktop:
    image: cytoscape/cytoscape-desktop:3.10.1
    ports:
      - '${NOVNC_PORT}:${NOVNC_PORT}'
    environment:
      - XVFB_SCREEN_WIDTH=${NOVNC_SCREEN_WIDTH}
      - XVFB_SCREEN_HEIGHT=${NOVNC_SCREEN_HEIGHT}
      - NOVNC_PORT=${NOVNC_PORT}
      - CYREST_PORT=${CYREST_PORT}