version: "2.2"
services:
  juypter:
    image: haeussma/pyeed-notebook:latest
    container_name: pyeed
    ports:
      - '${JUPYTER_PORT}:${JUPYTER_PORT}'

  cytoscape-desktop:
    image: cytoscape/cytoscape-desktop:3.10.1
    ports:
      - '${NOVNC_PORT}:${NOVNC_PORT}'
      - '${CYREST_PORT}:${CYREST_PORT}'
    container_name: cytoscape
    environment:
      - XVFB_SCREEN_WIDTH=${NOVNC_SCREEN_WIDTH}
      - XVFB_SCREEN_HEIGHT=${NOVNC_SCREEN_HEIGHT}
      - NOVNC_PORT=${NOVNC_PORT}
      - CYREST_PORT=${CYREST_PORT}